name: fvm
description: A simple cli to manage Flutter SDK versions per project. Support
  channels, releases, and local cache for fast switching between versions.
version: 2.2.4
homepage: https://github.com/leoafarias/fvm

environment:
  sdk: ">=2.12.0 <3.0.0"

executables:
  fvm: main

dependencies:
  args: ^2.1.0
  cli_notify: ^0.0.3
  cli_util: ^0.3.5
  console: ^4.1.0
  date_format: ^2.0.2
  io: ^1.0.0
  meta: ^1.3.0
  path: ^1.8.0
  process_run: ^0.12.1
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.1
  build_version: ^2.1.0
  effective_dart: ^1.3.2
  cli_pkg: ^1.5.1

  grinder: ^0.9.0
  test: ^1.17.11
  build_test: ^2.1.3
  test_cov: ^1.0.1
