name: Create Docker Release

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  deploy-docker:
    name: Docker Deploy (latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (latest)
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          file: ./.docker/Dockerfile
          push: true
          tags: leoafarias/fvm:latest

  # deploy-docker-latest:
  #   name: Docker Deploy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build and push
  #       id: docker_build
  #       uses: docker/build-push-action@v2
  #       with:
  #         file: ./.docker/Dockerfile
  #         push: true
  #         tags: leoafarias/fvm:${{ github.event.release.tag_name }}
  #         build-args: FVM_VERSION=${{ github.event.release.tag_name }}

  #     - name: Build and push Alpine image
  #       id: docker_build_alpine
  #       uses: docker/build-push-action@v2
  #       with:
  #         file: ./.docker/alpine/Dockerfile
  #         push: true
  #         tags: leoafarias/fvm-alpine:${{ github.event.release.tag_name }}
  #         build-args: FVM_VERSION=${{ github.event.release.tag_name }}
