name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: "${{ matrix.sdk-version }} / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        sdk-version: [stable] #, dev]
        include:
          - os: macOS-latest
            TARGET: macos
          - os: ubuntu-latest
            TARGET: linux
          - os: windows-latest
            TARGET: windows

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Setup Dart ${{ matrix.dart-version }}
        uses: DanTup/gh-actions/setup-dart@master
        with:
          channel: ${{ matrix.sdk-version }}

      - name: Install dependencies
        run: dart pub get

      - name: Run Test and Builder
        run: dart pub run build_runner test --delete-conflicting-outputs

  release:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    env:
      PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: dart pub get

      - name: Build Version Number
        run: dart pub run build_runner build --delete-conflicting-outputs

      - name: Deploy Github
        run: dart pub run grinder pkg-github-all

      - name: Deploy to Pub
        run: dart pub run grinder pkg-pub-deploy
